version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Running tests..."

  fork_guard:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Check fork status"
          command: |
            if [ -n "$CIRCLE_PR_USERNAME" ]; then
              echo "This is a forked PR. Skipping."
              circleci-agent step halt
            else
              echo "This is not a fork. Proceeding."
            fi

workflows:
  version: 2
  conditional_workflow:
    jobs:
      - fork_guard
      - approve_if_not_fork:
          type: approval
          requires:
            - fork_guard
      - run_tests:
          requires:
            - approve_if_not_fork
