version: 2.1

jobs:
  detect-fork:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Check if this is a fork"
          command: |
            if [ -n "$CIRCLE_PR_USERNAME" ]; then
              echo "This is a fork. Requiring approval."
              echo "export REQUIRE_APPROVAL=true" >> $BASH_ENV
            else
              echo "Internal PR or branch."
              echo "export REQUIRE_APPROVAL=false" >> $BASH_ENV
            fi
      - run: source $BASH_ENV

  hold-if-fork:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Approval step"
          command: echo "Waiting for approval"

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Running tests..."

workflows:
  fork-aware:
    jobs:
      - detect-fork
      - hold-if-fork:
          type: approval
          requires:
            - detect-fork
          filters:
            branches:
              only: /.*/  # adjust as needed
      - test:
          requires:
            - hold-if-fork
