version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Running tests..."

  fork_guard:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Check fork status"
          command: |
            if [ -n "$CIRCLE_PR_USERNAME" ]; then
              echo "This is a forked PR. Requiring approval."
              echo "true" > fork_status.txt
            else
              echo "This is not a fork. Proceeding."
              echo "false" > fork_status.txt
            fi
      - persist_to_workspace:
          root: .
          paths:
            - fork_status.txt

  approve_if_fork:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Check if approval needed"
          command: |
            if [ "$(cat fork_status.txt)" = "true" ]; then
              echo "Approval required for fork"
              exit 1
            else
              echo "No approval needed for internal PR"
              exit 0
            fi

workflows:
  version: 2
  conditional_workflow:
    jobs:
      - fork_guard
      - approve_if_fork:
          requires:
            - fork_guard
      - run_tests:
          requires:
            - fork_guard
            - approve_if_fork
